### ISSUE TITLE
ESP32 support

### ISSUE THREAD

**Issue by IPdotSetAF** [IPdotSetAF/ESPAsyncHTTPUpdateServer#2]
add support for ESP32 :)

**Comment by goebish** [comment]
I expected it to work on ESP32 as stated in the README but got this error:
The ESPAsyncHTTPUpdateServer library encountered an unknown path resolve error.D*: 2:10: fatal error: flash_hal.h: No such file or directory

**Comment by IPdotSetAF** [comment]
> I expected it to work on ESP32 as stated in the README but got this error: The ESPAsyncHTTPUpdateServer library encountered an unknown path resolve error.D*: 2:10: fatal error: flash_hal.h: No such file or directory

sorry, my bad. i was planning to add the support since its not much work but my dev system windows got corrupted. and the issue is left open. 

I will try to add it to the lib and publish it ASAP.

**Comment by IPdotSetAF** [comment]
Hey @goebish 
Sorry it took some time, I was a little busy.

Could you give it another try and let me know if your issue is fixed or not?
